set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports qb]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN V15 [get_ports d]
set_property PACKAGE_PIN T17 [get_ports q]
set_property PACKAGE_PIN R18 [get_ports qb]
