# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/project_codes/madesh_backup/EDGE_ZYNQ_7010_CODES/PL_EXAMPLES/CH6_XADC_WIFI/xadc_new.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
