set_property IOSTANDARD LVCMOS33 [get_ports {relay[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {relay[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN H20 [get_ports {relay[0]}]
set_property PACKAGE_PIN J20 [get_ports {relay[1]}]
set_property PACKAGE_PIN N17 [get_ports {switch[0]}]
set_property PACKAGE_PIN P18 [get_ports {switch[1]}]
