set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports Carry]
set_property IOSTANDARD LVCMOS33 [get_ports Sum]
set_property PACKAGE_PIN V15 [get_ports A]
set_property PACKAGE_PIN W15 [get_ports B]
set_property PACKAGE_PIN R18 [get_ports Carry]
set_property PACKAGE_PIN T17 [get_ports Sum]
